### ISSUE TITLE
Version info is wrong in VERSION.cmake for 1.1.008

### ISSUE THREAD

**Issue by barjac** [ptulp/polar_pi#10]
SET(PLUGIN_VERSION_MAJOR "1")
SET(PLUGIN_VERSION_MINOR "1")
SET(PLUGIN_VERSION_PATCH "007")
SET(PLUGIN_VERSION_DATE "2016-01-05")

I parse this to determine the current version when checking our Mageia package versions, it is useless if it does not correspond to the actual version.

**Comment by ptulp** [comment]
I don't know which file you are looking at, but the VERSION.cmake file in this repository is correct.
It shows:
SET(PLUGIN_VERSION_MAJOR "1")
SET(PLUGIN_VERSION_MINOR "1")
SET(PLUGIN_VERSION_PATCH "008")
SET(PLUGIN_VERSION_DATE "2017-05-31")

This was updated 2 years ago.

Regards,
Peter

**Comment by barjac** [comment]
I have always used https://github.com/nohal/polar_pi for polar, which I assume came from the opencpn website at some point. So is this now the 'real' upstream for this plugin?

**Comment by barjac** [comment]
OK the opencpn site does point here, but it still says that  1.1.007 is the latest release :/
Thanks for your help

**Comment by rgleason** [comment]
Try this one which compiles and works.
https://ci.appveyor.com/project/rgleason/plots-pi/builds/22729075/artifacts

Ptulp has merged the changes I believe.
https://github.com/rgleason/polar_pi/commits/master

The plugin compiles for opencpn 4.2   and loads polars.
