### ISSUE TITLE
ov50 - on rgleason branch - compile errors

### ISSUE THREAD

**Issue by rgleason** [ptulp/polar_pi#11]
rgleason polar_pi ov5 Branch
https://github.com/rgleason/polar_pi/commits/ov50

https://ci.appveyor.com/project/rgleason/polar-pi/builds/22824068
```
C:\project\polar_pi\build\package.vcxproj" (default target) (1) ->
"C:\project\polar_pi\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\project\polar_pi\build\polar_pi.vcxproj" (default target) (4) ->
(ClCompile target) -> 
  C:\project\polar_pi\src\PolarGui.cpp(290): error C2065: 'wxEVT_GRID_CELL_CHANGE': undeclared identifier [C:\project\polar_pi\build\polar_pi.vcxproj]
  C:\project\polar_pi\src\PolarGui.cpp(312): error C2065: 'wxEVT_GRID_CELL_CHANGE': undeclared identifier [C:\project\polar_pi\build\polar_pi.vcxproj]
  C:\project\polar_pi\src\PolarDialog.cpp(193): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'wxString' to 'int' [C:\project\polar_pi\build\polar_pi.vcxproj]
  C:\project\polar_pi\src\Polar.cpp(1159): error C2039: 'GetCols': is not a member of 'wxGrid' [C:\project\polar_pi\build\polar_pi.vcxproj]
  C:\project\polar_pi\src\Polar.cpp(1164): error C2039: 'GetRows': is not a member of 'wxGrid' [C:\project\polar_pi\build\polar_pi.vcxproj]
  C:\project\polar_pi\src\Polar.cpp(1168): error C2039: 'GetCols': is not a member of 'wxGrid' [C:\project\polar_pi\build\polar_pi.vcxproj]
    6 Warning(s)
    6 Error(s)

```

**Comment by rgleason** [comment]
wxEVT_GRID_CELL_CHANGED  is not supported in wxWidgets 3.1.2
We will have to find an alternative that is supported by wxWidgets 3.1.2

https://forums.wxwidgets.org/viewtopic.php?t=29916
https://docs.wxwidgets.org/stable/wx_wxgridevent.html#wxgrideventhttps://docs.wxwidgets.org/trunk/classwx_grid_event.html

EVT_GRID_CELL_CHANGED(func):
The user changed the data in a cell. The old cell value as string is available from GetString() event object method. Notice that vetoing this event still works for backwards compatibility reasons but any new code should only veto EVT_GRID_CELL_CHANGING event and not this one. Processes a wxEVT_GRID_CELL_CHANGED event type. 

Imcompatibility?

**PolarGui.cpp Line 290**

PolarGui.cpp(290): error C2065: 'wxEVT_GRID_CELL_CHANGE': undeclared identifier [

	m_gridEdit->Connect( wxEVT_GRID_CELL_CHANGE, wxGridEventHandler( PolarDlg::OnGridCellChange ), NULL, this );


**PolarGui.cpp   Line 312**

	m_gridEdit->Disconnect( wxEVT_GRID_CELL_CHANGE, wxGridEventHandler( PolarDlg::OnGridCellChange ), NULL, this );

**PolarDialog.cpp Line 193**
	m_gridEdit->SetCellValue(s,event.GetRow(),event.GetCol());
	}
	event.Skip();
}



Polar.cpp Line 1159

        else // CSV Format
      {
        wxString s = _T( "TWA\\TWS," ); 
     for ( int col = 0; col < dlg->m_gridEdit->GetCols(); col++ )
            s <<  dlg->m_gridEdit->GetColLabelValue( col )+_T( "," );
        s.RemoveLast();
        polarFile << s << _T( "\n" );

**Polar.cpp Line 1164**

        for ( int row = 0; row < dlg->m_gridEdit->GetRows(); row++ )


**Polar.cpp Line 1168**

            s = wxEmptyString;
			
			
http://forums.codeblocks.org/index.php?topic=21674.0

http://forums.codeblocks.org/index.php?topic=21674.0




I have just tried with rev 10922     "The 20 November 2016 build (10922)" and the problem is still the same. It looks like this ID has been discouraged for quite some time (deprecated?) and in wx3.1 it is gone. It is a problem when wxSmith still uses the now non-existent ID.

As a temporary work around I had to add in my code
#define wxEVT_GRID_CELL_CHANGE wxEVT_GRID_CELL_CHANGED

So, yes it is still a problem.


https://docs.wxwidgets.org/3.1/interface_2wx_2grid_8h.html#adac8c85b01fea02c2277c12189f39a28



https://docs.wxwidgets.org/3.1/interface_2wx_2grid_8h.html#adac8c85b01fea02c2277c12189f39a28

**Comment by rgleason** [comment]
This morning, looking at this again. I think this is the main problem 

C:\project\polar_pi\src\PolarDialog.cpp(193): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': **cannot convert argument 1 from 'wxString' to 'int'_** [C:\project\polar_pi\build\polar_pi.vcxproj]

**So perhaps the problem is in line 1159**   **wxString**
It cannot be converted to 'int'!

```
wxString s = _T( "TWA\\TWS," ); 
 for ( int col = 0; col < dlg->m_gridEdit->GetCols(); col++ )
        s <<  dlg->m_gridEdit->GetColLabelValue( col )+_T( "," );
    s.RemoveLast();
```
The program is using wxString to transfer an integer. Doesn't make sense. Is there a 'wxInt' [?

Coverting everything to and from wxString](https://wiki.wxwidgets.org/Converting_everything_to_and_from_wxString)

Here is what that says:

```
wxString to integer number

wxString number(wxT("145"));
long value;
if(!number.ToLong(&value)) { /* error! */ }

or

wxString str = _T("123");
int num;

num = wxAtoi(str);

```

**Comment by ptulp** [comment]
Rick,
Could you try on line 193 in PolarDialog.cpp the following:
m_gridEdit->SetCellValue(event.GetRow(),event.GetCol(), s);

Apparently the old line is deprecated.
I still have problems to get my environment on wxwidgets 3.1.2 running so I cannot compiled myself at the moment.

Regards,
Peter

**Comment by rgleason** [comment]
Thank you Peter! Will do this this afternoon.
If you turn on appveyor for this plugin, it will build it for you!
I don't have a dev env for ov50 either, using appveyor. Very helpful thing, but slow, but you can multitask.

**Comment by rgleason** [comment]
```
C:\project\polar_pi\build\polar_pi.vcxproj" (default target) (4) ->
(ClCompile target) -> 
  C:\project\polar_pi\src\Polar.cpp(1248): warning C4018: '<': signed/unsigned mismatch [C:\project\polar_pi\build\polar_pi.vcxproj]
  C:\project\polar_pi\src\Polar.cpp(1295): warning C4018: '<': signed/unsigned mismatch [C:\project\polar_pi\build\polar_pi.vcxproj]
  C:\project\polar_pi\src\Polar.cpp(1321): warning C4018: '<': signed/unsigned mismatch [C:\project\polar_pi\build\polar_pi.vcxproj]
"C:\project\polar_pi\build\package.vcxproj" (default target) (1) ->
"C:\project\polar_pi\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\project\polar_pi\build\polar_pi.vcxproj" (default target) (4) ->
(ClCompile target) -> 
  C:\project\polar_pi\src\PolarGui.cpp(290): error C2065: 'wxEVT_GRID_CELL_CHANGE': undeclared identifier [C:\project\polar_pi\build\polar_pi.vcxproj]
  C:\project\polar_pi\src\PolarGui.cpp(312): error C2065: 'wxEVT_GRID_CELL_CHANGE': undeclared identifier [C:\project\polar_pi\build\polar_pi.vcxproj]
  C:\project\polar_pi\src\Polar.cpp(1159): error C2039: 'GetCols': is not a member of 'wxGrid' [C:\project\polar_pi\build\polar_pi.vcxproj]
  C:\project\polar_pi\src\Polar.cpp(1164): error C2039: 'GetRows': is not a member of 'wxGrid' [C:\project\polar_pi\build\polar_pi.vcxproj]
  C:\project\polar_pi\src\Polar.cpp(1168): error C2039: 'GetCols': is not a member of 'wxGrid' [C:\project\polar_pi\build\polar_pi.vcxproj]
    6 Warning(s)
    5 Error(s
```

**Comment by ptulp** [comment]
Rick,

Change 'wxEVT_GRID_CELL_CHANGE' to 'wxEVT_GRID_CELL_CHANGED' and
Change 'GetCols' to GetNumberCols' and
Change 'GetRows' to GetNumberRows'

Success,
Peter

**Comment by rgleason** [comment]
```
/*       m_gridEdit->SetCellValue(s,event.GetRow(),event.GetCol()); */
         m_gridEdit->SetCellValue(event.GetNumberRows(),event.GetNumberCols(), s);
	}
	event.Skip();

```
Made the changes and got these errors

>  C:\project\polar_pi\src\PolarGui.cpp(290): error C2065: 'wxEVT_GRID_CELL_CHANGE': undeclared identifier [C:\project\polar_pi\build\polar_pi.vcxproj]

  
  Line 290 
`  	m_gridEdit->Connect( wxEVT_GRID_CELL_CHANGE, wxGridEventHandler( PolarDlg::OnGridCellChange ), NULL, this );`
  

>   C:\project\polar_pi\src\PolarGui.cpp(312): error C2065: 'wxEVT_GRID_CELL_CHANGE': undeclared identifier [C:\project\polar_pi\build\polar_pi.vcxproj]

  
  Line 312
 ` 	m_gridEdit->Disconnect( wxEVT_GRID_CELL_CHANGE, wxGridEventHandler( PolarDlg::OnGridCellChange ), NULL, this );`
  

>   C:\project\polar_pi\src\PolarDialog.cpp(194): error C2039: 'GetNumberRows': is not a member of 'wxGridEvent' [C:\project\polar_pi\build\polar_pi.vcxproj]

  
  Line 194
 `         m_gridEdit->SetCellValue(event.GetNumberRows(),event.GetNumberCols(), s);`
  

>   C:\project\polar_pi\src\PolarDialog.cpp(194): error C2039: 'GetNumberCols': is not a member of 'wxGridEvent' [C:\project\polar_pi\build\polar_pi.vcxproj]

  
  Line 194
`            m_gridEdit->SetCellValue(event.GetNumberRows(),event.GetNumberCols(), s);`

>   C:\project\polar_pi\src\Polar.cpp(1159): error C2039: 'GetCols': is not a member of 'wxGrid' [C:\project\polar_pi\build\polar_pi.vcxproj]

  
  Line 1159
```
          wxString s = _T( "TWA\\TWS," );
        for ( int col = 0; col < dlg->m_gridEdit->GetCols(); col++ )

```

>   C:\project\polar_pi\src\Polar.cpp(1164): error C2039: 'GetRows': is not a member of 'wxGrid' 
>   [C:\project\polar_pi\build\polar_pi.vcxproj]

 
  Line 1164
`         for ( int row = 0; row < dlg->m_gridEdit->GetRows(); row++ )
`

>  C:\project\polar_pi\src\Polar.cpp(1168): error C2039: 'GetCols': is not a member of 'wxGrid' [C:\project\polar_pi\build\polar_pi.vcxproj]

   Line 1168
`            for ( int col = 0; col < dlg->m_gridEdit->GetCols(); col++ )`

Peter, Can you advise what changes need to be made?

**Comment by ptulp** [comment]
Rick,

Maybe I should have been more specific:
In file PolarGui.cpp line 290, change 'wxEVT_GRID_CELL_CHANGE' to  "
'wxEVT_GRID_CELL_CHANGED' 
In file PolarGui.cpp line 312, change 'wxEVT_GRID_CELL_CHANGE' to  "
'wxEVT_GRID_CELL_CHANGED' 

In file Polar.cpp line 1159 change 'GetCols' to GetNumberCols'
In file Polar.cpp line 1159 change 'GetRows' to GetNumberRows'
In file Polar.cpp line 1159 change 'GetCols' to GetNumberCols'

Do NOT change file PolarDialog.cpp line 194, so leave that be 
      m_gridEdit->SetCellValue(event.GetRow(),event.GetCol(), s);

Success,
Peter

**Comment by rgleason** [comment]
That's done now. Hope it works. I partially understand, but until I can do a wiring diagram of what is dependent on what and how this works, I'll not be able to make good changes. Thanks.

Just ran across the exact same problems with Findit_pi.  Hopefully I can apply what we learned here.

**Comment by rgleason** [comment]
Should I change GetRows and GetCols to GetNumberCols and GetNumberRows now?

```
ClCompile target) -> 
  C:\project\polar_pi\src\PolarDialog.cpp(194): error C2039: 'GetRows': is not a member of 'wxGridEvent' [C:\project\polar_pi\build\polar_pi.vcxproj]
  C:\project\polar_pi\src\PolarDialog.cpp(194): error C2039: 'GetCols': is not a member of 'wxGridEvent' [C:\project\polar_pi\build\polar_pi.vcxproj]
    6 Warning(s)
    2 Error(s)
Time Elapsed 00:01:32.96
```

**Comment by ptulp** [comment]
Rick,

Do you have a document how to use appveyor?
Then I could run it myself?

Peter

**Comment by rgleason** [comment]
I changed line 194   in PolarDialog.cpp  changing GetCols and GetRows
 to GetNumberCols and GetNumberRows.  - makes no difference I guess, not a member of wxGridEvent.

So it should be changed back I guess.

"C:\project\polar_pi\build\package.vcxproj" (default target) (1) ->
"C:\project\polar_pi\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\project\polar_pi\build\polar_pi.vcxproj" (default target) (4) ->
(ClCompile target) -> 
  C:\project\polar_pi\src\PolarDialog.cpp(194): error C2039: 'GetNumberRows': is not a member of 'wxGridEvent' [C:\project\polar_pi\build\polar_pi.vcxproj]
  C:\project\polar_pi\src\PolarDialog.cpp(194): error C2039: 'GetNumberCols': is not a member of 'wxGridEvent' [C:\project\polar_pi\build\polar_pi.vcxproj]
    6 Warning(s)
    2 Error(s

**Comment by rgleason** [comment]
Peter if you were to make a new branch from being on your master.
git checkout master
git checkout -b ov50   you'll be put on the ov50 branch.
Then make a PR from my branch ov50 and merge it.
(Or I can then make a PR to your new ov50 branch for you to merge.)

Then if your branch ov50 is active you can edit the appveyor.yml file yourself and save it. Or any other file.
Then you have to do
git status
git add  [all the modified files]
git commit -a -m "your commit message here"
git push [your remote upstream repos - I use "origin"] ov50
Then find the appveyor checkmark , green orange or red and right click down to the "console tab" (middle lower right).  The the file will be found under the "Artifacts Tab" if it succeeded.  If there is a red check I still go and check to see if there is a file, because if there are no errors, there is usually one.

**Comment by ptulp** [comment]
Rick,

Line 194 should be 
m_gridEdit->SetCellValue(s,event.GetRow(),event.GetCol());

So NOT GetRows or GetCols. it should be singular.

Peter

**Comment by ptulp** [comment]
Does appveyor works for all platforms eg OSX??

**Comment by rgleason** [comment]
Gee, it really has to be exact. I don't pick up on this stuff too fast.

Actually .travis will build OSX I believe. 
Sean and Pavel have some examples. I don't know anything about osx so I try to ignore those conditionals.  Leamas is starting to do mingw too.

Here is an example from Sean for ov42 I believe.
https://github.com/seandepagnier/weather_routing_pi/blob/master/.travis.yml

It would be great if we could have a good section in .travis for all the plugins for compiling for OSX! It could make getting OSX plugins less trouble, and faster for you too. 

Thanks saw your note about diner. Will push on, and let you know.

**Comment by rgleason** [comment]
Changed this as directed:
PolarDialog.cpp
```
Line 194 should be
m_gridEdit->SetCellValue(s,event.GetRow(),event.GetCol());

So NOT GetRows or GetCols. it should be singular.
```

Result

```
ClCompile target) -> 
  C:\project\polar_pi\src\PolarDialog.cpp(194): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'wxString' to 'int' [C:\project\polar_pi\build\polar_pi.vcxproj]
    6 Warning(s)
    1 Error(s)
```

I think it is the first argument    "s"   cannot be converted from wxstring to integer.  It have been complaining about this a lot, leaving warnings only, now it is an error.

I'll have to find out what "s" means. in  m_gridEdit somehow.

**Comment by rgleason** [comment]
Found it line  178  in  PolarDialog.cpp

```
wxString s = m_gridEdit->GetCellValue(event.GetRow(),event.GetCol());
	polar->setValue(s,event.GetRow(),event.GetCol(),true);
	bool comma = false;
```

It looks to me like they're trying to use wxString s  to store true or false?  
I am still trying to think in Pascal, which I could learn by reading!  This isnt that kind of language.

**Comment by ptulp** [comment]
Rick,

Sorry my fault, line 194 should be:
m_gridEdit->SetCellValue(event.GetRow(), event.GetCol(), s);

Hope this helps.
Peter

**Comment by rgleason** [comment]
Not yours, it was the that way at the beginning. It compiles now. Thank you.
I'm finished bugging you now. 
Will ask Kathi to link to Rasbats repos for now. We can straighten things out later.
Thanks.
